FROM openjdk:17-jdk-slim

WORKDIR /code

# TODO 実行手順まで持っていきたい
# COPY . /code/
# RUN ./gradlew clean build -x test
# RUN cp build/libs/*.jar /app.jar
# ENTRYPOINT ["java", "-jar", "/app.jar"]
